name: Latest GitHub Activity
on:
  schedule:
    # Runs every Sunday at midnight.
    - cron: '0 0 * * 0'
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly.

jobs:
  update-readme-with-activity:
    name: Update this repo's README with latest GitHub activity
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Readme-Workflows/recent-activity@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
