name: Cache GitHub README Stats

on:
  schedule:
    # Runs every day at midnight.
    - cron: "0 0 * * *"
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly.

jobs:
  download-assets:
    name: Download assets
    runs-on: ubuntu-latest
    steps:
      - name: Download the stats file
        run: curl 'https://github-readme-stats-stevenjdh.vercel.app/api?username=stevenjdh&show_icons=true&hide_border=true' -o stats.svg

      - name: Download the top languages file
        run: curl 'https://github-readme-stats-stevenjdh.vercel.app/api/top-langs/?username=stevenjdh&layout=compact&hide_border=true&langs_count=8' -o top-langs.svg

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: assets
          path: |
            stats.svg
            top-langs.svg

  push-assets:
    name: Push assets
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    needs: [download-assets]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: assets
          path: assets

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(assets): update cached GRS files"
          branch: main
          file_pattern: 'assets/*.svg'
          commit_user_name: github-readme-stats 🤖
          commit_user_email: actions@github.com
          commit_author: github-readme-stats 🤖 <actions@github.com>